---
title: "Demo RplotterPkg::create_table()"
author: "Rick Dean"
date: "1/17/2021"
output: html_document
---

```{r}
library(kableExtra)
library(knitr)
library(RplotterPkg)
library(data.table)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Add a "Car" column to `mtcars`:
```{r}
data("mtcars")
mtcars_dt <- data.table::setDT(mtcars, keep.rownames = T)
data.table::setnames(mtcars_dt, old = "rn", new = "Car")
```

```{r, fig.width=8, fig.height=6}
new_table <- RplotterPkg::create_table(
  x = mtcars_dt[1:5, 1:6]
)
new_table
```
```{r kable, results="asis"}
x <- mtcars_dt[1:20, 1:6]
scroll_table <- create_table(
  x = mtcars[1:20, 1:6],
  caption = "Car mpg  car mpg  car mpg car mpg  ",
  align_v = c("l",rep("c", 5)),
  position = "left",
  full_width = T,
  fixed_thead = T,
  head_bkgd = "purple",
  head_col = "white",
  head_sz = 22,
  footnote = "mtcars",
  footnote_title = "Source:",
  borders = T,
  border_sz = 3,
  border_col = "green",
  scroll_height = "200px",
  hide_hor_scrollbar = T
)
scroll_table
```

